### ISSUE TITLE
Github only supports TLS 1.2, gem panics 

### ISSUE THREAD

**Issue by adamdecaf** [ddollar/github-backup#21]
I was running `v0.10.0` and ran into the following error: 

```
/usr/lib/ruby/1.9.1/net/http.rb:799:in `connect': SSL_connect returned=1 errno=0 state=unknown state: tlsv1 alert protocol version (Faraday::SSLError)
	from /usr/lib/ruby/1.9.1/net/http.rb:799:in `block in connect'
	from /usr/lib/ruby/1.9.1/timeout.rb:54:in `timeout'
	from /usr/lib/ruby/1.9.1/timeout.rb:99:in `timeout'
	from /usr/lib/ruby/1.9.1/net/http.rb:799:in `connect'
	from /usr/lib/ruby/1.9.1/net/http.rb:755:in `do_start'
	from /usr/lib/ruby/1.9.1/net/http.rb:744:in `start'
	from /usr/lib/ruby/1.9.1/net/http.rb:1284:in `request'
	from /usr/lib/ruby/1.9.1/net/http.rb:1026:in `get'
```

**Comment by adamdecaf** [comment]
Just a quick `bundle update` fixes the problem locally for me.
